EFIRM/Models/ServiceReportsViewModels.cs
using System;
using System.Collections.Generic;
using System.Web;

namespace EFIRM.Models
{
	public class ServiceReportsViewModels
	{
		public IList<ServiceReportsModels> Items { get; set; }

		//used for paggination
		public Pager Pager { get; set; }
	}

	public class ServiceReportsModels
	{
		public int Id { get; set; }
		public Nullable<int> FacilityId { get; set; }
		public Nullable<int> WorkOrderId { get; set; }
		public string WORefNo { get; set; }
		public string ContractCoverage { get; set; }
		public Nullable<int> BuildingId { get; set; }
		public Nullable<int> FloorId { get; set; }
		public Nullable<int> AreaId { get; set; }
		public string ContactNo { get; set; }
		public string ContactEmail { get; set; }
		public string RequestType { get; set; }
		public Nullable<int> AssetTypeId { get; set; }
		public Nullable<int> AssetId { get; set; }
		public Nullable<int> ServiceStatus { get; set; }
		public Nullable<bool> CustomerSignOffreceived { get; set; }
		public string UploadSR { get; set; }
		public string ServiceReportNo { get; set; }
		public string ReportDate { get; set; }
		public Nullable<bool> NotificationSend { get; set; }
		public Nullable<int> MaintenanceTaskId { get; set; }
		public string SignaturePath { get; set; }
		public Nullable<int> CategoryIdParentId { get; set; }
		public Nullable<int> CategoryTypeId { get; set; }
		public Nullable<bool> WorkHazardous { get; set; }
		public Nullable<bool> TestedForDefect { get; set; }
		public string Status { get; set; }
		public string Comments { get; set; }
		public Nullable<int> RoomId { get; set; }
		public Nullable<int> CustomerFeedbackId { get; set; }
		public Nullable<int> ReportSignedUserId { get; set; }
		public string RequestorDescription { get; set; }
		public string UserName { get; set; }
		public string UserNumber { get; set; }
		public string Facility { get; set; }
		public string Building { get; set; }
		public string Floor { get; set; }
		public string Area { get; set; }
		public string Room { get; set; }
	}
}

EFIRM/Controllers/ServiceReportsController.cs
using EFIRM.DAL;
using EFIRM.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace EFIRM.Controllers
{
	[Authorize]
	public class ServiceReportsController : BaseController
	{
		// GET: ServiceReports
		public ActionResult Index(int? page)
		{
			ServiceReportsViewModels Model = new ServiceReportsViewModels();
			Model.Items = new List<ServiceReportsModels>();
			var TempModelList = new List<ServiceReportsModels>();
			var tblWorkkOrders = tblWorkOrder;
			var tblFacilities = db.tblFacilities.ToList();
			var tblBuildings = db.tblBuildings.ToList();
			var tblFloors = db.tblFloors.ToList();
			var tblAreas = db.tblAreas.ToList();
			var tblRooms = db.tblRooms.ToList();
			//var tblServiceRequests = db.tblServiceRequests.ToList();
			//var tblWorkOrders = db.tblWorkOrders.ToList();
			Model.Pager = new Pager(tblWorkkOrders.Count(), page);
			List<int?> WorkOrderIdList = new List<int?>();
			foreach (var WorkOrder in tblWorkkOrders.Skip((Convert.ToInt32(page) * Model.Pager.PageSize)).Take(Model.Pager.PageSize))
			{

				ServiceReportsModels ServiceReportsModel = new ServiceReportsModels
				{
					WORefNo = WorkOrder.WorkOrderRefNo,
					ReportDate =
					(Convert.ToDateTime(WorkOrder.WorkOrderDate)).ToString("yyyy/MM/dd, hh:mm:ss tt")
				};

				ServiceReportsModel.RequestorDescription = WorkOrder.tblServiceRequest.RequestDescription;
				ServiceReportsModel.UserName = WorkOrder.tblServiceRequest.ContactName;
				ServiceReportsModel.UserNumber = WorkOrder.tblServiceRequest.ContactNumber;

				ServiceReportsModel.FacilityId = WorkOrder.tblServiceRequest.FacilityId;
				ServiceReportsModel.Facility = tblFacilities.Where(x => x.Id == ServiceReportsModel.FacilityId)?.FirstOrDefault().FacilityName;

				ServiceReportsModel.BuildingId = WorkOrder.tblServiceRequest.BuildingId;
				ServiceReportsModel.Building = tblBuilding.Where(x => x.Id == ServiceReportsModel.BuildingId)?.FirstOrDefault().BuildingName;

				ServiceReportsModel.FloorId = WorkOrder.tblServiceRequest.FloorId;
				ServiceReportsModel.Floor = (ServiceReportsModel.FloorId != null && ServiceReportsModel.FloorId != 0) ?
					tblFloors.Where(x => x.Id == ServiceReportsModel.FloorId).FirstOrDefault()?.FloorName : string.Empty;

				ServiceReportsModel.AreaId = WorkOrder.tblServiceRequest.AreaId;
				ServiceReportsModel.Area = (ServiceReportsModel.AreaId != null && ServiceReportsModel.AreaId != 0) ?
					tblAreas.Where(x => x.Id == ServiceReportsModel.AreaId).FirstOrDefault()?.AreaName : string.Empty;

				ServiceReportsModel.RoomId = WorkOrder.tblServiceRequest.RoomId;
				ServiceReportsModel.Room = (ServiceReportsModel.RoomId != null && ServiceReportsModel.RoomId != 0) ?
					tblRooms.Where(x => x.Id == ServiceReportsModel.RoomId).FirstOrDefault()?.RoomName : string.Empty;

				ServiceReportsModel.Status = WorkOrder.Status;

				Model.Items.Add(ServiceReportsModel);
			}

			return View(Model);
		}

		// Get details of selected service report
		public ActionResult Edit(string WORefNo)
		{
			ServiceRequestsModels ServiceRequestsViewModel = new ServiceRequestsModels();

			var tblServiceReport = db.tblServiceReports.Where(x => x.WORefNo == WORefNo).FirstOrDefault();
			var tblWorkOrder = db.tblWorkOrders.Where(x => x.WorkOrderRefNo == WORefNo).FirstOrDefault();
			var tblServiceRequest = db.tblServiceRequests.
				 Where(x => x.Id == tblWorkOrder.ServiceRequestId).FirstOrDefault();

			ServiceRequestsViewModel.OccupantName = tblServiceRequest.OccupantName;
			ServiceRequestsViewModel.Occupant = db.tblOccupants.Where(x => x.Id == tblServiceRequest.OccupantName).FirstOrDefault()?.OccupantName;
			ServiceRequestsViewModel.ServiceRequestNumber = tblServiceRequest.ServiceRequestNumber;
			ServiceRequestsViewModel.ContactName = tblServiceRequest.ContactName;
			ServiceRequestsViewModel.ContactNumber = tblServiceRequest.ContactNumber;
			ServiceRequestsViewModel.ContactEmail = tblServiceRequest.ContactEmail;
			ServiceRequestsViewModel.Facility = db.tblFacilities.Where(x => x.Id == tblServiceRequest.FacilityId).FirstOrDefault()?.FacilityName;
			ServiceRequestsViewModel.Building = db.tblBuildings.Where(x => x.Id == tblServiceRequest.BuildingId).FirstOrDefault()?.BuildingName;
			ServiceRequestsViewModel.Floor = db.tblFloors.Where(x => x.Id == tblServiceRequest.FloorId).FirstOrDefault()?.FloorName;
			ServiceRequestsViewModel.Area = db.tblAreas.Where(x => x.Id == tblServiceRequest.AreaId).FirstOrDefault()?.AreaName;
			ServiceRequestsViewModel.Room = db.tblRooms.Where(x => x.Id == tblServiceRequest.RoomId).FirstOrDefault()?.RoomName;
			Int32.TryParse(tblServiceRequest.RequestType, out int RequestType);
			ServiceRequestsViewModel.RequestType = RequestType;
			ServiceRequestsViewModel.AssetGroupId = tblServiceRequest.AssetGroupId;
			ServiceRequestsViewModel.Category = db.tblCategories.Where(x => x.Id == tblServiceRequest.CategoryId).FirstOrDefault()?.CategoryName;
			ServiceRequestsViewModel.RequestDescription = tblServiceRequest.RequestDescription;
			ServiceRequestsViewModel.ISeniorTechId = tblServiceRequest.ISeniorTechId;
			ServiceRequestsViewModel.SeverityName = db.tblSeverities.Where(x => x.Id == tblServiceRequest.Severity).FirstOrDefault()?.SeverityLevel;
			ServiceRequestsViewModel.RequestTypeName = db.tblServiceTypes.Where(x => x.Id == ServiceRequestsViewModel.RequestType).FirstOrDefault()?.ServiceDescription;
			ServiceRequestsViewModel.Group = db.tblAssetGroups.Where(x => x.Id == tblServiceRequest.AssetGroupId).FirstOrDefault()?.AssetGroup;
			ServiceRequestsViewModel.Status = tblServiceRequest.Status;

			var TblWorkOrder = db.tblWorkOrders.Where(x => x.ServiceRequestId == tblServiceRequest.Id).FirstOrDefault();

			var TblWorkOrderResources = db.tblWorkOrderResources.Where(x => x.WorkOrderId == TblWorkOrder.Id).Select(y => y.WorkforceId).ToList();

			var TblWorkForces = db.tblWorkForces;

			var ResourceList =
				from tblWorkForces in TblWorkForces
				where TblWorkOrderResources.Contains(tblWorkForces.Id)
				select tblWorkForces;

			ServiceRequestsViewModel.Resources = ResourceList.Select(x => x.PersonName).ToList();
			ServiceRequestsViewModel.ISeniorTech = TblWorkForces.Where(x => x.Id == tblServiceRequest.ISeniorTechId).FirstOrDefault()?.PersonName;
			ServiceRequestsViewModel.FilesUploaded = new List<string>();
			ServiceRequestsViewModel.FilesUploaded = db.tblServiceRequestImages.Where(x => x.nServiceRequestId == tblServiceRequest.Id).Select(x => x.sImageName).ToList();
			var ServiceReport = db.tblServiceReports.Where(x => x.WorkOrderId == TblWorkOrder.Id).FirstOrDefault();
			ServiceRequestsViewModel.Comments = ServiceReport?.Comments;
			try
			{
				if (!string.IsNullOrEmpty(ServiceReport?.SignaturePath))
				{
					string path = Path.Combine("C:\\Program Files (x86)\\Johnson Controls\\EFIRM\\ImagesSignature\\",
															   Path.GetFileName(ServiceReport?.SignaturePath));
					using (Image image = Image.FromFile(path))
					{
						using (MemoryStream m = new MemoryStream())
						{
							image.Save(m, image.RawFormat);
							byte[] imageBytes = m.ToArray();

							// Convert byte[] to Base64 String
							ServiceRequestsViewModel.DigitalSignatureImageData = Convert.ToBase64String(imageBytes);
						}
					}
				}
			}
			catch (Exception ex)
			{

			}
			ServiceRequestsViewModel.WorkOrderId = TblWorkOrder.Id;
			ServiceRequestsViewModel.WorkOrderRef = WORefNo;
			return View(ServiceRequestsViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(ServiceRequestsModels Model)
		{
			if (ModelState.IsValid)
			{
				var TblServiceReport = db.tblServiceReports.Where(x => x.WorkOrderId == Model.WorkOrderId)?.FirstOrDefault();

				var tblServiceRequest = db.tblServiceRequests.
						 Where(x => x.ServiceRequestNumber == Model.ServiceRequestNumber).FirstOrDefault();

				var TblWorkOrder = db.tblWorkOrders.Where(x => x.ServiceRequestId == tblServiceRequest.Id)?.FirstOrDefault();

				if (tblServiceReport == null)
				{
					var tblServiceReport = new tblServiceReport();

					tblServiceReport.ContactNo = tblServiceRequest.ContactNumber;
					tblServiceReport.ContactEmail = tblServiceRequest.ContactEmail;
					tblServiceReport.FacilityId = tblServiceRequest.FacilityId;
					tblServiceReport.BuildingId = tblServiceRequest.BuildingId;
					tblServiceReport.FloorId = tblServiceRequest.FloorId;
					tblServiceReport.AreaId = tblServiceRequest.AreaId;
					tblServiceReport.RoomId = tblServiceRequest.RoomId;
					tblServiceReport.RequestType = tblServiceRequest.RequestType;
					tblServiceReport.AssetTypeId = tblServiceRequest.AssetTypeId;
					tblServiceReport.CategoryIdParentId = tblServiceRequest.CategoryIdParentId;
					tblServiceReport.ServiceReportNo = Model.ServiceRequestNumber;
					tblServiceReport.ReportDate = DateTime.Now;
					tblServiceReport.Status = "Acknowledged";

					tblServiceReport.WorkOrderId = TblWorkOrder.Id;
					tblServiceReport.WORefNo = TblWorkOrder.WorkOrderRefNo;

					tblServiceRequest.Status = "Acknowledged";
					TblWorkOrder.Status = "Acknowledged";
					tblServiceRequest.AcknowledgeDate = DateTime.Now;

					tblServiceRequestStatu TBLStatus = new tblServiceRequestStatu();
					TBLStatus.dtTimeStamp = DateTime.Now;
					TBLStatus.iServiceRequestId = tblServiceRequest.Id;
					TBLStatus.iServiceRequestStatusId = db.TblServiceStates.Where(x => x.ServiceState == "Acknowledged").FirstOrDefault().id;
					db.tblServiceRequestStatus.Add(TBLStatus);

					db.tblServiceReports.Add(tblServiceReport);

					db.SaveChanges();
					TblServiceReport = tblServiceReport;
				}
				if (!string.IsNullOrEmpty(Model.DigitalSignatureImageData))
				{
					Model.DigitalSignatureImageData = Model.DigitalSignatureImageData.Replace("data:image/png;base64,", String.Empty);
					string filename = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString()

EFIRM/Views/ServiceReports/Index.cshtml
@model EFIRM.Models.ServiceReportsViewModels
@{
	ViewBag.Title = "Service Reports";
	Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}

<h4>Service Reports</h4>
<hr />
<div class="row mb-5">
	<div class="col-md-12">
		<div class="table-responsive table-striped">
			<table class="table table-hover align-middle">
				<thead class="thead-light">
					<tr>
						<th>
							@Html.Raw("Work Order Number")
						</th>
						<th>
							@Html.Raw("Date and Time")
						</th>
						<th>
							@Html.Raw("Request Description")
						</th>
						<th>
							@Html.Raw("User Name")
						</th>
						<th>
							@Html.Raw("User Number")
						</th>
						<th>
							@Html.Raw("Facility")
						</th>
						<th>
							@Html.Raw("Building")
						</th>
						<th>
							@Html.Raw("Floor")
						</th>
						<th>
							@Html.Raw("Area")
						</th>
						<th>
							@Html.Raw("Room")
						</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.Items)
					{
						<tr>
							<td>

								@{ string color = "black";}
								@if (item.Status.Equals("Rectified", StringComparison.OrdinalIgnoreCase))
								{
									color = "lawngreen";
								}
								@if (item.Status.Equals("Open", StringComparison.OrdinalIgnoreCase))
								{
									color = "red";
								}
								@if (item.Status.Equals("Acknowledged", StringComparison.OrdinalIgnoreCase))
								{
									color = "#e9d700";
								}
								@if (item.Status.Equals("Cancelled", StringComparison.OrdinalIgnoreCase))
								{
									color = "blue";
								}
								@if (item.Status.Equals("Completed", StringComparison.OrdinalIgnoreCase))
								{
									color = "black";
								}

								<a style="font-size:larger;color:@color" href="@Url.Action("Edit", "ServiceReports", new { WORefNo = item.WORefNo })">
									@Html.DisplayFor(modelItem => item.WORefNo)
								</a>
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.ReportDate)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.RequestorDescription)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.UserName)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.UserNumber)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Facility)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Building)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Floor)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Area)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Room)
							</td>
						</tr>
					}

				</tbody>
			</table>
			<!-- pager -->
			<nav aria-label="...">
				@if (Model.Pager.EndPage > 1)
				{
					<ul class="pagination">
						@if (Model.Pager.CurrentPage > 1)
						{
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceReports/Index">First</a>
							</li>
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceReports/Index?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
							</li>
						}

						@for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
						{
							<li class="paginate_button page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
								<a class="page-link" href="~/ServiceReports/Index?page=@page">@page</a>
							</li>
						}

						@if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
						{
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceReports/Index?page=@(Model.Pager.CurrentPage + 1)">Next</a>
							</li>
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceReports/Index?page=@(Model.Pager.TotalPages)">Last</a>
							</li>
						}
					</ul>
				}
			</nav>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$('#SR').addClass("active");
	});
</script>