EFIRM/Models/ServiceRequestsViewModels.cs
using System;
using System.Collections.Generic;
using System.Web;

namespace EFIRM.Models
{
	public class ServiceRequestsViewModels
	{
		public IList<ServiceRequestsModels> Items { get; set; }

		//used for paggination
		public Pager Pager { get; set; }

	}

	public class ServiceRequestsModels
	{
		public int Id { get; set; }
		public Nullable<int> FacilityId { get; set; }
		public string Facility { get; set; }
		public string ServiceRequestNumber { get; set; }
		public int? OccupantName { get; set; }
		public string Occupant { get; set; }
		public Nullable<int> BuildingId { get; set; }
		public string Building { get; set; }
		public Nullable<int> FloorId { get; set; }
		public string Floor { get; set; }
		public Nullable<int> AreaId { get; set; }
		public string Area { get; set; }
		public string ContactNumber { get; set; }
		public string ContactEmail { get; set; }
		public int RequestType { get; set; }
		public string RequestDate { get; set; }
		public Nullable<int> AssetTypeId { get; set; }
		public Nullable<int> AssetId { get; set; }
		public string RequestDescription { get; set; }
		public Nullable<int> ConfirmSLA { get; set; }
		public Nullable<int> Severity { get; set; }
		public string RequestMode { get; set; }
		public string StatusUpdatePreference { get; set; }
		public Nullable<int> AssignedTo { get; set; }
		public Nullable<System.DateTime> RequestClosureBy { get; set; }
		public string AcknowledgedBy { get; set; }
		public string Status { get; set; }
		public Nullable<int> ServiceTypeId { get; set; }
		public Nullable<int> CategoryId { get; set; }
		public string ContactName { get; set; }
		public string WhoLogged { get; set; }
		public Nullable<System.DateTime> AcknowledgeDate { get; set; }
		public Nullable<System.DateTime> ClosingDate { get; set; }
		public Nullable<int> CategoryIdParentId { get; set; }
		public string SpecialInstructionForServiceRequest { get; set; }
		public Nullable<bool> IsThroughService { get; set; }
		public Nullable<int> RoomId { get; set; }
		public string Room { get; set; }
		public Nullable<int> ISeniorTechId { get; set; }
		public string ISeniorTech { get; set; }
		public Nullable<int> AssetGroupId { get; set; }
		public Nullable<System.DateTime> RectificationDateTime { get; set; }
		public string ChangeRequestTypeStatus { get; set; }
		public List<HttpPostedFileBase> Files { get; set; }
		public List<string> FilesUploaded { get; set; }
		public int[] ResourceID { get; set; }
		public List<string> Resources { get; set; }
		public string Group { get; set; }
		public string RequestTypeName { get; set; }
		public string Category { get; set; }
		public string SeverityName { get; set; }
		//Below are used in service reports
		public string Comments { get; set; }
		public string DigitalSignatureImageData { get; set; }
		public int WorkOrderId { get; set; }
		public string WorkOrderRef { get; set; }
	}
}

EFIRM/Controllers/ServiceRequestsController.cs
using EFIRM.DAL;
using EFIRM.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;

namespace EFIRM.Controllers
{
	[Authorize]
	public class ServiceRequestsController : BaseController
	{
		// GET: ServiceRequests
		public ActionResult Index(int? page, bool ServiceRequestCreated = false)
		{
			ServiceRequestsViewModels Model = new ServiceRequestsViewModels
			{
				Items = new List<ServiceRequestsModels>()
			};

			var tblServiceRequests = tblServiceRequest;
			var tblFacilities = db.tblFacilities.ToList();
			var tblBuildings = db.tblBuildings.ToList();
			var tblFloors = db.tblFloors.ToList();
			var tblAreas = db.tblAreas.ToList();
			var tblRooms = db.tblRooms.ToList();
			Model.Pager = new Pager(tblServiceRequests.Count(), page);

			foreach (var ServiceRequest in tblServiceRequests.Skip((Convert.ToInt32(page) * Model.Pager.PageSize)).Take(Model.Pager.PageSize))
			{
				ServiceRequestsModels ServiceRequestModel = new ServiceRequestsModels
				{
					ServiceRequestNumber = ServiceRequest.ServiceRequestNumber,
					RequestDate = (Convert.ToDateTime(ServiceRequest.RequestDate)).ToString("yyyy/MM/dd, hh:mm:ss tt"),
					RequestDescription = ServiceRequest.RequestDescription,
					ContactName = ServiceRequest.ContactName,
					ContactNumber = ServiceRequest.ContactNumber,
					Status = ServiceRequest.Status,
					FacilityId = ServiceRequest.FacilityId,
					Facility = (ServiceRequest.FacilityId != null && ServiceRequest.FacilityId != 0) ?
					tblFacilities.Where(x => x.Id == ServiceRequest.FacilityId).FirstOrDefault()?.FacilityName : string.Empty,

					BuildingId = ServiceRequest.BuildingId,
					Building = (ServiceRequest.BuildingId != null && ServiceRequest.BuildingId != 0) ?
				tblBuildings.Where(x => x.Id == ServiceRequest.BuildingId).FirstOrDefault()?.BuildingName : string.Empty,

					FloorId = ServiceRequest.FloorId,
					Floor = (ServiceRequest.FloorId != null && ServiceRequest.FloorId != 0) ?
				  tblFloors.Where(x => x.Id == ServiceRequest.FloorId).FirstOrDefault()?.FloorName : string.Empty,

					AreaId = ServiceRequest.AreaId,
					Area = (ServiceRequest.AreaId != null && ServiceRequest.AreaId != 0) ?
					tblAreas.Where(x => x.Id == ServiceRequest.AreaId).FirstOrDefault()?.AreaName : string.Empty,

					RoomId = ServiceRequest.RoomId,
					Room = (ServiceRequest.RoomId != null && ServiceRequest.RoomId != 0) ?
					tblRooms.Where(x => x.Id == ServiceRequest.RoomId).FirstOrDefault()?.RoomName : string.Empty
				};

				Model.Items.Add(ServiceRequestModel);
			}

			if (ServiceRequestCreated)
				ViewBag.ServiceRequestCreated = true;

			return View(Model);
		}

		// GET: ServiceRequests/Create
		public ActionResult Create()
		{
			ViewBag.Occupants = new SelectList(db.tblOccupants, "Id", "OccupantName");
			ViewBag.Facilities = new SelectList(db.tblFacilities, "Id", "FacilityName");
			ViewBag.Groups = new SelectList(db.tblAssetGroups.OrderBy(x => x.AssetGroup), "Id", "AssetGroup");
			ViewBag.RequestTypes = new SelectList(db.tblServiceTypes, "Id", "ServiceDescription");
			ViewBag.Severities = new SelectList(db.tblSeverities, "Id", "SeverityLevel");
			var ResquestDescription = db.tblRequestDescriptions.Select(x => x.RequestDescription).ToList();
			ViewBag.RequestDescriptionDropDown = JsonConvert.SerializeObject(ResquestDescription);

			//For tenant
			if (!Convert.ToString(Session["UserRole"]).ToLower().Contains("admin"))
			{
				var WorkForceId = Convert.ToInt32(Session["WorkForceId"]);
				var Occupant = db.tblOccupants.Where(x => x.Id == WorkForceId).FirstOrDefault();

				if (Occupant != null)
				{
					ViewBag.TenantOcuupantId = Occupant.Id;
					ViewBag.TenantFacilityId = Occupant.FacilityId;
					ViewBag.TenantBuildingId = Occupant.BuildingId;
					ViewBag.TenantFloorId = Occupant.FloorId;
					ViewBag.RoomId = Occupant.RoomId;
					ViewBag.AreaId = Occupant.AreaId;
					ViewBag.ContactName = Occupant.ContactName;
					ViewBag.ContactNumber = Occupant.ContactNumber;
					ViewBag.ContactEmail = Occupant.ContactEmail;
				}

				ViewBag.Occupants = new SelectList(db.tblOccupants.Where(x => x.Id == Occupant.Id), "Id", "OccupantName");

			}

			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(ServiceRequestsModels ServiceRequest)
		{
			if (ModelState.IsValid)
			{
				var RequestId = Convert.ToInt32(ServiceRequest.RequestType);
				var requesttype = db.tblServiceTypes.Where(x => x.Id == RequestId).FirstOrDefault()?.ServiceDescription;

				if (!string.IsNullOrEmpty(ServiceRequest.Area))
				{
					var TblArea = new tblArea
					{
						FacilityId = ServiceRequest.FacilityId,
						BuildingId = ServiceRequest.BuildingId,
						FloorId = ServiceRequest.FloorId,
						AreaName = ServiceRequest.Area
					};
					//TblArea.Id = db.tblAreas.Max(p => p.Id) + 1;
					db.tblAreas.Add(TblArea);
					db.SaveChanges();
					ServiceRequest.AreaId = TblArea.Id;
				}

				if (!string.IsNullOrEmpty(ServiceRequest.Room))
				{
					var TblRoom = new tblRoom
					{
						FacilityId = ServiceRequest.FacilityId,
						BuildingId = ServiceRequest.BuildingId,
						FloorId = ServiceRequest.FloorId,
						AreaId = ServiceRequest.AreaId,
						RoomName = ServiceRequest.Room
					};
					//TblRoom.Id = db.tblRooms.Max(p => p.Id) + 1;
					db.tblRooms.Add(TblRoom);
					db.SaveChanges();
					ServiceRequest.RoomId = TblRoom.Id;
				}

				var TblServiceRequest = new tblServiceRequest
				{
					OccupantName = ServiceRequest.OccupantName,
					ContactName = ServiceRequest.ContactName,
					ContactNumber = ServiceRequest.ContactNumber,
					ContactEmail = ServiceRequest.ContactEmail,
					FacilityId = ServiceRequest.FacilityId,
					BuildingId = ServiceRequest.BuildingId,
					FloorId = ServiceRequest.FloorId,
					AreaId = ServiceRequest.AreaId,
					RoomId = ServiceRequest.RoomId,
					RequestType = Convert.ToString(ServiceRequest.RequestType),
					AssetGroupId = ServiceRequest.AssetGroupId,
					CategoryId = ServiceRequest.CategoryId,
					AssetTypeId = ServiceRequest.CategoryId,
					RequestDescription = ServiceRequest.RequestDescription,
					ISeniorTechId = ServiceRequest.ISeniorTechId,
					Severity = ServiceRequest.Severity ?? 3,
					WhoLogged = System.Web.HttpContext.Current.User.Identity.Name,
					Status = "Open",
					RequestDate = System.DateTime.Now,
					IsThroughService = false,
					CategoryIdParentId= Convert.ToInt32(db.tblServiceTypes.Where(x=>x.Id == ServiceRequest.RequestType).FirstOrDefault()?.ServiceType)
				};
				string ServiceRequestNumber = string.Empty;
				var LastServiceRequestNumber = (db.tblServiceRequests.Where(y => y.ServiceRequestNumber.Contains(requesttype)).OrderByDescending(x => x.Id).FirstOrDefault()?.ServiceRequestNumber).Split('/'); ;
				DateTime LastServiceRequestNumberDate = DateTime.ParseExact(LastServiceRequestNumber[2], "yyMMdd", CultureInfo.InvariantCulture);

				if (LastServiceRequestNumberDate.Year == DateTime.Today.Year &&
					LastServiceRequestNumberDate.Month == DateTime.Today.Month)
				{
					ServiceRequestNumber = "SR/" + requesttype + "/" +
						DateTime.Today.ToString("yy") + DateTime.Now.Month.ToString("d2") +
						DateTime.Now.Day.ToString("d2")
						+ "/" + (Convert.ToInt32(LastServiceRequestNumber[3]) + 1);

				}
				else
				{

					ServiceRequestNumber = "SR/" + requesttype + "/" +
						DateTime.Today.ToString("yy") + DateTime.Now.Month.ToString("d2") +
						DateTime.Now.Day.ToString("d2")
							+ "/" + 1;
				}
				TblServiceRequest.ServiceRequestNumber = ServiceRequestNumber;
				db.tblServiceRequests.Add(TblServiceRequest);
				db.SaveChanges();


				string WorkOrderRefNumber = string.Empty;
				var LastWorkOrderRefNumber = (db.tblWorkOrders.Where(y => y.WorkOrderRefNo.Contains(requesttype)).OrderByDescending(x => x.Id).FirstOrDefault()?.WorkOrderRefNo).Split('/'); ;
				DateTime LastWorkOrderRefNumberDate = DateTime.ParseExact(LastWorkOrderRefNumber[2], "yyMMdd", CultureInfo.InvariantCulture);
				var WorkOrderId = Convert.ToInt32(ServiceRequest.RequestType);

				if (LastWorkOrderRefNumberDate.Year == DateTime.Today.Year &&
					LastWorkOrderRefNumberDate.Month == DateTime.Today.Month)
				{
					WorkOrderRefNumber = "WO/" + requesttype + "/" +
						DateTime.Today.ToString("yy") + DateTime.Now.Month.ToString("d2") +
						DateTime.Now.Day.ToString("d2")
						+ "/" + (Convert.ToInt32(LastWorkOrderRefNumber[3]) + 1);

				}
				else
				{

					WorkOrderRefNumber = "WO/" + requesttype + "/" +
						DateTime.Today.ToString("yy") + DateTime.Now.Month.ToString("d2") +
						DateTime.Now.Day.ToString("d2")
							+ "/" + 1;
				}

				var TblWorkOrders = new tblWorkOrder
				{
					WorkOrderRefNo = WorkOrderRefNumber,
					ServiceRequestId = TblServiceRequest.Id,
					WorkOrderDate = DateTime.Now,
					Status = "Open",
					RequesterId = Convert.ToInt32(Session["UserID"]),
					CategoryTypeId = ServiceRequest.CategoryId,					
					IsThroughService = false,
					CategoryIdParentId = Convert.ToInt32(db.tblServiceTypes.Where(x => x.Id == ServiceRequest.RequestType).FirstOrDefault()?.ServiceType)

				};
				db.tblWorkOrders.Add(TblWorkOrders);
				db.SaveChanges();

				var NewServiceRequest = tblServiceRequest.Where(x => x.ServiceRequestNumber == ServiceRequestNumber)?.FirstOrDefault();
				List<int> ResourcesList = new List<int>();
				//Adding reosurces in tblWorkOrderResource
				if (ServiceRequest.ResourceID != null && ServiceRequest.ResourceID.Any())
				{
					foreach (var resource in ServiceRequest.ResourceID)
					{
						ResourcesList.Add(resource);
						var Tblworkorderresources = new tblWorkOrderResource
						{
							WorkforceId = resource,
							WorkOrderId = TblWorkOrders.Id
						};

						var TblServiceRequestResources = new tblServiceRequestResource

EFIRM/Views/ServiceRequests/Index.cshtml
@model EFIRM.Models.ServiceRequestsViewModels

@{
	ViewBag.Title = "Service Request";
	Layout = "~/Views/Shared/_DashBoardLayout.cshtml";
}
<div class="row mb-5">
	<div class="col-md-12">
		@if (ViewBag.ServiceRequestCreated == true)
		{
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<strong>Service Request Created Successful!</strong>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		}
			<h4>Service Requests</h4>
		<hr />
		<div class="table-responsive table-striped">
			<table class="table table-hover align-middle">
				<thead class="thead-light">
					<tr>
						<th>
							@Html.Raw("Service Request Number")
						</th>
						<th>
							@Html.Raw("Date & Time")
						</th>
						<th>
							@Html.Raw("Request Description")
						</th>
						<th>
							@Html.Raw("User Name")
						</th>
						<th>
							@Html.Raw("User Number")
						</th>
						<th>
							@Html.Raw("Facility")
						</th>
						<th>
							@Html.Raw("Building")
						</th>
						<th>
							@Html.Raw("Floor")
						</th>
						<th>
							@Html.Raw("Area")
						</th>
						<th>
							@Html.Raw("Room")
						</th>
						<th>
							@Html.Raw("Action")
						</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.Items)
					{
						<tr>
							<td>
								@{ string color = "black";}
								@if (item.Status.Equals("Rectified", StringComparison.OrdinalIgnoreCase))
								{
									color = "lawngreen";
								}
								@if (item.Status.Equals("Open", StringComparison.OrdinalIgnoreCase))
								{
									color = "red";
								}
								@if (item.Status.Equals("Acknowledged", StringComparison.OrdinalIgnoreCase))
								{
									color = "#e9d700";
								}
								@if (item.Status.Equals("Cancelled", StringComparison.OrdinalIgnoreCase))
								{
									color = "blue";
								}
								@if (item.Status.Equals("Completed", StringComparison.OrdinalIgnoreCase))
								{
									color = "black";
								}

								<a style="font-size:larger;color:@color" href="@Url.Action("Edit", "ServiceRequests", new { ServiceRequestNumber = item.ServiceRequestNumber })">
									@Html.DisplayFor(modelItem => item.ServiceRequestNumber)
								</a>
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.RequestDate)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.RequestDescription)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.ContactName)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.ContactNumber)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Facility)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Building)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Floor)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Area)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Room)
							</td>
							<td>
								
								<a class="btn btn-success btn-sm waves-effect waves-light"
								    href="@Url.Action("CreatePdf", "ServiceRequests", new { ServiceRequestNumber = item.ServiceRequestNumber })">
									<i class="batch-icon batch-icon-browser-alt-download"></i>
								</a>
							</td>
						</tr>
					}

				</tbody>
			</table>
			<!-- pager -->
			<nav aria-label="...">
				@if (Model.Pager.EndPage > 1)
				{
					<ul class="pagination">
						@if (Model.Pager.CurrentPage > 1)
						{
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceRequests/Index">First</a>
							</li>
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceRequests/Index?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
							</li>
						}

						@for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
						{
							<li class="paginate_button page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
								<a class="page-link" href="~/ServiceRequests/Index?page=@page">@page</a>
							</li>
						}

						@if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
						{
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceRequests/Index?page=@(Model.Pager.CurrentPage + 1)">Next</a>
							</li>
							<li class="paginate_button page-item">
								<a class="page-link" href="~/ServiceRequests/Index?page=@(Model.Pager.TotalPages)">Last</a>
							</li>
						}
					</ul>
				}
			</nav>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$('#VSR').addClass("active");
	});
</script>